### ISSUE TITLE
As a user I should be able to log into the application with my Email or Facebook.

### ISSUE THREAD

**Issue by KevinMaldjian** [nyu-software-engineering/nyu-barter#2]
## Estimation of Work
L

## Acceptance Criteria
- [x] Attach firebase to the web and iOS app 
- [x] Enable Facebook user authorization on firebase
- [x] Attach Facebook SDK to app 
- [x] Create facebook deveolper page and link to app 
- [x] When a user creates an account, their information must be transferred from the authentication section of firebase to the real-time database.

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-nyu-barter - this user story is in the "In Progress" column on your task board.   User stories must stay in the Sprint Backlog column.  Only tasks and spikes can travel down other columns.
